### ISSUE TITLE
**-Info.plist这个是不是应该直接就是Info.plist

### ISSUE THREAD

**Issue by lizhaobomb** [debugtalk/JenkinsTemplateForApp#10]
IOError: [Errno 2] No such file or directory: '/Users/**/.jenkins/jobs/**/workspace/**-Info.plist'

这个是问题怎么解决呢是不是应该直接就是Info.plist

**Comment by debugtalk** [comment]
这取决于生成的plist文件名称；你先确认下生成的plist文件路径在哪儿
