### ISSUE TITLE
jenkins build history中二维码不显示

### ISSUE THREAD

**Issue by liuyuanming** [debugtalk/JenkinsTemplateForApp#2]
内容如标题

**Comment by debugtalk** [comment]
@liuyuanming 可参考[《关于持续集成打包平台的Jenkins配置和构建脚本实现细节》](http://debugtalk.com/post/iOS-Android-Packing-with-Jenkins-details/)中“展示二维码图片”部分。

**Comment by liuyuanming** [comment]
就是参考了 出不来 好像根本识别不了图片。
![1](https://cloud.githubusercontent.com/assets/11534449/17454494/8e687aa8-5bca-11e6-9277-19321e0c2704.png)
![2](https://cloud.githubusercontent.com/assets/11534449/17454493/8db54672-5bca-11e6-871e-23e681ef577f.png)
![3](https://cloud.githubusercontent.com/assets/11534449/17454496/a0cc181c-5bca-11e6-8819-a126933dc95d.png)
![4](https://cloud.githubusercontent.com/assets/11534449/17454501/e442cc1c-5bca-11e6-8ce5-6f803b9312c5.png)

**Comment by liuyuanming** [comment]
这些配置都没错啊，而且本地文件夹下也有二维码图片

**Comment by debugtalk** [comment]
看了你的截图，不是Jenkins识别不了图片，应该是你图片引用的地址和你archive的地址不一致的原因。你可以试着先在Jenkins网页中通过浏览器的Inspector查看下【\n】前的值。
