### ISSUE TITLE
ipa包上传蒲公英时报错

### ISSUE THREAD

**Issue by liuyuanming** [debugtalk/JenkinsTemplateForApp#5]
![2016-08-11 6 38 56](https://cloud.githubusercontent.com/assets/11534449/17586249/19e29452-5ff3-11e6-8f50-97c5e1c37b6d.png)

**Comment by debugtalk** [comment]
这个问题我也遇到过，是蒲公英平台的HTTP上传接口不稳定，换成HTTPS的会好点。另外，看这报错提示，你应该还用的以前的代码，建议pull最新的代码。
